//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using ECS;
using System.Collections;

public class Game : MonoBehaviour
{
	//The title of the game
	public String gameTitle = "Default Title";
	
	//The controls. Please use a fine description.
	public String controls = "WASD";

	//Default value = false. If description should be logged, choose the gameObject 
	//which holds this script and enable printControls in Components Game script
	public bool printControls = false;

	void Start ()
	{
		Debug.Log ("Game start");
		Debug.Log ("Welcome to " + gameTitle);
		if (printControls) {
			Debug.Log (controls);
		}
		foreach (GameObject g in GameObject.FindObjectsOfType(typeof(GameObject))) {
			switch(g.tag){
				case "Player":
					generatePlayer ();
					g.AddComponent(typeof(PlayerComponent));
				//g.AddComponent(typeof(PlayerComponent));
					break;
				case "Enemy":
					generateEnemy();
					break;
				case "Object":
				default:
					break;
			}
		}
		EntityManager.printStatus ();
	}

	void Update(){
		ECSEngine.mainLoop (Time.deltaTime);
	}

	public void generatePlayer(){
		int playerID = EntityManager.generateEntity ();
		EntityManager.addComponent(playerID, typeof(PlayerComponent));
		EntityManager.addComponent(playerID, typeof(InputComponent));
	}

	public void generateEnemy(){
		int enemyID = EntityManager.generateEntity ();
		EntityManager.addComponent(enemyID, typeof(EnemyComponent));
	}


}


