//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ECS;
using UnityEngine;

public class PhysicComponent : IComponent
{
	private Vector2 m_position;
	private Vector2 m_velocity;
	private Rigidbody2D m_rigidBody;
	private Collider2D m_collider;

	public PhysicComponent (Vector2 position, Vector2 velocity)
	{
		m_position = position;
		m_velocity = velocity;
	}

	public PhysicComponent (Vector2 position, Vector2 velocity, Collider2D collider)
		:this(position, velocity)
	{
		m_collider = collider;
		m_rigidBody = m_collider.attachedRigidbody;
	}

	public PhysicComponent (Vector2 position, Vector2 velocity, Rigidbody2D rigidBody) 
		: this (position, velocity)
	{
		m_rigidBody = rigidBody;
	}

	override public void reset(){

	}

	public Vector2 getPosition(){
		return m_position;
	}

	public void setPosition(Vector2 position){
		m_position = position;
	}

	public Vector2 getVelocity(){
		return m_velocity;
	}

	public void setVelocity(Vector2 velocity){
		m_velocity = velocity;
	}

	public Rigidbody2D getRigidBody(){
		return m_rigidBody;
	}

	//Dont know yet if this function is needed.
	public void setRigidBody(Rigidbody2D rigidBody){
		m_rigidBody = rigidBody;
	}

	public Collider2D getCollider(){
		return m_collider;
	}

	//Dont know yet if this function is needed.
	public void setCollider(Collider2D collider){
		m_collider = collider;
	}
	

}


